### ISSUE TITLE
\n

### ISSUE THREAD

**Issue by Mboukhal** [TN19N/exam06-mini_serv#1]
Your program must not contains #define preproc

do that mean "#define"  is forbidden

msg in normal way hase "\n", i think you don't  have to add it:

[                            sprintf(buffer2, "client %d: %s\n", clientId, msg);](https://github.com/TN19N/exam06-mini_serv/blob/5cafbe4a85997e2b2b9159a658ea6bfd085b4fa0/mini_serv.c#L130C28-L130C80)

**Comment by TN19N** [comment]
- you are right about "#define" it is safer to not use them in the actual exam.
- about "\n" when I parse the buffer, I remove the new line if it exists.
